### ISSUE TITLE
Minor: Typo in manual page footers

### ISSUE THREAD

**Issue by robert914** [3noix/UJPS#13]
The PDF manual footer on each page still says: "UJPS V2.1.6 Manual" even though the manual version / title page states version 2.3.1. Just thought you should know.

**Comment by 3noix** [comment]
Indeed the V2.1.6 is a typo. But the V2.3.1 was not, it is just because I did not updated the documentation since V2.3.1... and there was no need in fact, the little corrections need no documentation modification. I corrected it and specified V2.3.3 everywhere. I will use a "Word property field" to avoid such errors in the future.

**Comment by 3noix** [comment]
There must be a lot a other mistakes in the pdf, as I don't speak english so well... I am French, but good in english for a French :-). The football (soccer for you) game France - USA is about to begin!

**Comment by robert914** [comment]
No worries! Just noticed it while scanning the manual and thought I should mention it. Your english is quite good BTW.

Go USA! :-)
