### ISSUE TITLE
Problem: Why won't this send key press to Star Citizen?

### ISSUE THREAD

**Issue by robert914** [3noix/UJPS#15]
I have the following mapping and callback:
```
    Map(xbc, ControlType::Axis, XBC::THUMBLY, AllLayers, new TriggerAxisChange{},
        new ActionCallback([this]() { this->throttleAxis(); }));
```
callback:
```
void Profile::throttleAxis()
{
    // raw input XBC Y-axis is forward=negative, back=positive
    // so make sure to invert polarity so forward=positive, back=negative
    float rawY = -xbc->axisValue(XBC::THUMBLY);
    if (rawY >= 0)
    {
        // set forward motion flag
        bMovingForward = true;
        // zero out backward longitudinal strafe axis
        vjoy->setAxis(VJOY::Y, 0.0f);
        // forward stick movement is relative throttle axis
        vjoy->setAxis(VJOY::SLIDER0, rawY);
    }
    else
    {
        // reset throttle to zero on transition from forward to reverse
        if (bMovingForward)
            DoAction(new ActionKeyPulse{Key_0, 0, pulseCycles});
        // disable forward motion flag (backward now)
        bMovingForward = false;
        // zero out relative throttle axis (0=zero throttle)
        vjoy->setAxis(VJOY::SLIDER0, 0.0f);
        // backward stick movement is backward longitudinal strafe
        vjoy->setAxis(VJOY::Y, rawY);
    }
}
```

My intent is that forward on stick is throttle relative in SC, and pull back should zero the throttle and then use backward strafe. I have Key 0 bound as zero throttle in SC bindings. When I test this with Monitoring0/1/2 and an open terminal window. It properly sends the "0" key press to the terminal whenever I start to pull back on the stick. However, in SC, it will never zero the throttle (it's like it never gets the Key_0 press). If I manually press "0" on the keyboard, it does zero my throttle.

I've tried increasing the pulse time (I currently use what you did):
```
    const uint pulseTime = 150; // ms
    pulseCycles = ms2cycles(pulseTime);
```
I've even tried doubling the pulse time.

Any ideas why this doesn't work?

**Comment by robert914** [comment]
If I change the DoAction to a button like this:
```
            DoAction(new ActionButtonPulse{vjoy, SCJ::ThrottleZero, pulseCycles});
```
And add that binding in SC, then it works perfectly fine, it just won't work when sending a key pulse.
I don't understand why this won't work with a Key_0 pulse? Can you see why?

**Comment by 3noix** [comment]
It is weird. I quickly made a few test, and I see a difference with what I obtained a few months ago. With this code...:
```
Map(tmwj, ControlType::Button, TMWJ::H3L, AllLayers, new TriggerButtonPress{},  new ActionKeyPress{Key_A});
	Map(tmwj, ControlType::Button, TMWJ::H3R, AllLayers, new TriggerButtonPress{},  new ActionKeyRelease{Key_A});
	Map(tmwj, ControlType::Button, TMWJ::H3D, AllLayers, new TriggerButtonChange{}, new ActionKeySetChange{Key_B});
```

... a few months ago, when the focus is in notepad++, auto-repeat was working, but not anymore. Probably a change due to a Windows update.

**Comment by 3noix** [comment]
I found an interesting lead with this: https://stackoverflow.com/questions/18647053/sendinput-not-equal-to-pressing-key-manually-on-keyboard-in-c
... working on it!

**Comment by robert914** [comment]
Oh good, I was hoping it wasn't just my setup.

**Comment by 3noix** [comment]
No difference about the auto-repeat with the modification described in this article... and I have a doubt about the config I used to see auto-repeat, maybe it was with Thrustmaster TARGET.

**Comment by 3noix** [comment]
There is also another possibility: the windows protection that improved... there are protections to prevent hacking by keyboard. Maybe it is because of that.

**Comment by 3noix** [comment]
Today I looked deeper into the problem. And the solution was indeed to use hardware scan codes instead of virtual key codes (as in the link above). In fact, when I tested it, it was only by checking the auto-repeat on a text editor... and the auto-repeat did not work but in fact it is another issue (it seems that the keyboards send press events for each repetition!). So I tested it with Star Citizen and it works... but I have seen other issues in SC controls (unmapped default bindings are not really removed and it can generate multiple actions!).

**Comment by 3noix** [comment]
There is a little drawback to this modification: for now there is less keys available... hardware scan key codes are not generic, and have also other problems: for example the "left arrow" key code and the "numpad 4" key code are the same (even if there is seperate "left arrow" key)... so when numlock is on, I have no way for now to generate a "left arrow" keystroke.

But I think there might be some sort of modifier to do so.. but I will have to go deeper in it.

By checking the modifications I did it "WindowsKeys.h" you can see all the keys I had to remove because of such issues.

**Comment by robert914** [comment]
I did some simple tests, and the key pulse handling appears to be working OK now. Thanks!
