### ISSUE TITLE
Request: Add Xbox 360 controller support

### ISSUE THREAD

**Issue by robert914** [3noix/UJPS#3]
I don't see any include files or DLLs for support of Xbox controllers? Does that mean I can't use UJPS to map my Xbox controller to vJoy? If not, what do you need in order to add this? I can help code it, if I know what you need me to do. Thanks!

**Comment by robert914** [comment]
FYI - Just noticed on page 11 of the manual where you state that:

> For now I provide only a few plugins, because it needs to be tested to be sure that the names and the buttons or axes matches and I and my friends only own a few of them. But don’t hesitate to contact me if you want that I do one for your controller. Just tell me with no ambiguity which physical axis/button matches which axis/button in Monitoring1 and what names you want, I will do the plugin and share with everyone. In the meantime you should not be blocked.

I'll take a look and either provide you the information, or I can probably code up plugins for them based on your existing ones.

**Comment by robert914** [comment]
Attached is a header file defining the button/axis names to the indexes reported by the monitor program. I have not created the CODE files yet.

[MicrosoftXbox360Controller.h](https://github.com/3noix/UJPS/files/2052218/MicrosoftXbox360Controller.h.txt)

I used names that mostly matched what made sense, and leveraged some of the same names that Star Citizen uses in the bindings file. Feel free to change if you want.

**Comment by 3noix** [comment]
As for Thrustmaster T16000M, I would need its exact name as seen by joy.cpl or MonitoringX.

I don't have an Xbox 360 controller, so I have a few questions for you to be sure of what I am doing. Are the left and right triggers 2 independent axes... physically I mean. According to what I have red sometime ago, there are physically independent, but DirectInput sees them as a single axis. Is that right? And if you use the 2 triggers at the same time, how it behaves (as seen from MonitoringX)? It performs a sum?

If the answer is yes, the only way to see the 2 independent axes in UJPS tool would be to use XInput instead of DirectInput in case of an Xbox 360 controller.

**Comment by robert914** [comment]
Ok, so, the exact name that appears in joy.cpl or MonitoringX is: "Controller (XBOX 360 For Windows)"
I have the Xbox 360 Wired Controller, so I'm assuming the wireless one would appear the same, but I cannot verify that.

As for the Axis on the triggers:
- Yes, each trigger is a separate "physical button" that can be pressed in
- When pressing the Left Trigger down, it moves the Axis 4 from 0 to -1000, and when you depress the Right Trigger down it moves the Axis 4 from 0 to 1000.
- When pressing both Left and Right Trigger fully down, they sum to value of 0.
- If you press them unequal amounts, they sum and show the difference.

So I guess if you are able to process the Xbox controller as an XInput device, that is more correct for what type of device it is, since they are two independent axis that can be depressed. However, if this is not possible with UJPS due to your architecture, then I can manage with having just a "Trigger Axis" that is a single axis (representing both triggers as one axis) that I can bind for now (I'll likely use it for something like Strafe or Roll anyway where it would be fine this way).

**Comment by 3noix** [comment]
I updated and added the Xbox 360 controller plugin into the master branch. Let me know if there is any issue with it.

For now the 2 triggers are seen as a merged axis. I will try to use XInput later.

**Comment by robert914** [comment]
Thanks! I’ll hopefully have some time tonight to try it out

**Comment by 3noix** [comment]
In the last commit I added support of the 2 independent triggers of the Xbox 360 gamepads... to do so I modified again QtGameControllerModif so that it can use both DirectInput and XInput. Let me know if it works as expected. So far I have seen no regression with my controllers.

I still have to add the vibration feature in the plugin... I will provide it in the setData function.

**Comment by 3noix** [comment]
And I also added the vibration feature in the plugin.

**Comment by robert914** [comment]
Thanks for this! I'll give it a try this week, I've been busy with other stuff lately.
