### ISSUE TITLE
Request: Add Thrustmaster T.16000M support

### ISSUE THREAD

**Issue by robert914** [3noix/UJPS#4]
Similar question as my Xbox controller issue. Do you need help setting up a T.16000M joystick plugin? I don't see one in your include/plugins setup. I do see that you have the TWCS throttle that comes with the T.16000M FCS set (which is what I actually own). So I'm assuming we'd need to code up the T.16000M support, since you have the TWCS already? Note: We would need to support the right/left configuration as well, since some people have two T.16000M devices and fly dual stick.

**Comment by robert914** [comment]
FYI - Just noticed on page 11 of the manual where you state that:

> For now I provide only a few plugins, because it needs to be tested to be sure that the names and the buttons or axes matches and I and my friends only own a few of them. But don’t hesitate to contact me if you want that I do one for your controller. Just tell me with no ambiguity which physical axis/button matches which axis/button in Monitoring1 and what names you want, I will do the plugin and share with everyone. In the meantime you should not be blocked.

I'll take a look and either provide you the information, or I can probably code up plugins for them based on your existing ones.

**Comment by robert914** [comment]
Attached is a header file defining the button/axis names to the indexes reported by the monitor program. I have not created the CODE files yet.
[ThrustmasterT16000MJoystick.h](https://github.com/3noix/UJPS/files/2052215/ThrustmasterT16000MJoystick.h.txt)

**Comment by 3noix** [comment]
Ok, perfect, thanks for your help. Compared to your header file, I just swapped the THR and RUDDER axes to put them in the same order as in the TARGET GUI... this swap is done in the sources have written (otherwise it will obviously be inconsistent).

There is just info missing: what is the exact name of the joystick in joy.cpl or in MonitoringX? And does the name change (along with PID) when the switch position (the one under the base) is changed between left and right?

**Comment by 3noix** [comment]
I created a new branch "Controllers-plugins-dev" where I put my modifications for T16000M.

**Comment by robert914** [comment]
Ok, the exact name in joy.cpl and MonitoringX is: "T.16000M"

As for the Left/Right hand switch, the name remains the same. However, in the joy.cpl Properties, it does show in there "Left Handed" or "Right Handed" at the top. But the actual name of the device is the same. I seem to remember reading someplace in the TARGET docs or someone's dual stick samples, that there is a way to tell which mode it's in.

**Comment by 3noix** [comment]
Ha, it is not as simple as I thought... according to "target.tmh", in left-handed mode, PID should be "b10b". How old are your thrustmaster drivers? Because old ones does not make the difference.

extract of "target.tmh":
`alias RMFD 		= "VID_044F&PID_b352", HCougar	= "VID_044F&PID_0400", T16000	= "VID_044F&PID_B10A";
alias TWCSThrottle	= "VID_044F&PID_B687", TFRPRudder="VID_044F&PID_B679", T16000L	= "VID_044F&PID_B10B";`

**Comment by robert914** [comment]
Hmm, that is weird. I'm pretty sure I have the latest drivers. I was under the same impression as you, that one should be b10a and the other b10b, but I was confused when it didn't show that. Let me go test some more...

**Comment by robert914** [comment]
I wonder, is it possible it only shows up as B10B when you actually have two devices plugged in, and if only one device is present, it's only B10A? I don't have two sticks, so I can't verify that, but it is a possibility.

**Comment by 3noix** [comment]
Indeed, I did not think about that one. We will need someone with 2 T16000M to figure it out.

**Comment by robert914** [comment]
Thanks! I’ll hopefully have some time tonight to try it out
