### ISSUE TITLE
Enhancement: Can we have a preference to define location of Profiles directory?

### ISSUE THREAD

**Issue by robert914** [3noix/UJPS#7]
Currently, the UJPS main UI always defaults to the "Profiles" directory provided with the source of UJPS. I'm creating my profiles in a separate directory that I'd like to set as the default path for the "Browse" button. Could this be added? It doesn't have to be a UI based setting, if you want to just provide an XML, INI, JSON or other external file in say %USERPROFILE%/AppData/Local/UJPS or somewhere I can create manually that it would read, that would be fine. I'm trying to keep all my profiles in a separate repository so that I can upload them to GitHub separately for others to access (if they want). I don't want to have to push them to the fork of UJPS or to your repo since they are custom created. And it would be nice if I could set that directory as default so I don't have to navigate to it all the time (and I don't really want to be modifying your source files locally unless I'm working on a patch / fix / enhancement to submit to you, because I can just modify the ApplicationSettings.xml file, but I really don't want to be doing that as a general practice).

Thanks!

BTW - I am *really* loving this tool! I love that I can create / program all my joysticks how I want, and it has allowed me to address issues I had with Joystick Gremlin where there is no option in it to properly reset axis when you use shift or mode switching on an axis (i.e. Gremlin always retains the current axis value when you shift to another axis, and there's no nice way to fix this without adding extra flat 0 curves ... messy!). Thanks so much!

**Comment by 3noix** [comment]
In fact the UJPS app already provides that using the first item of the toolbar: you don't have to edit manually the ApplicationsSettings.xml file. You have 2 options: the fixed "profiles directory", and using the last selected one. Let me know if you see any interesting improvement to do.

There is also a tab for activating the call of vJoyConfig.exe from UJPS but I do not recommend you to use it because:
- I have seen that it does not work correctly if you want to do it for several vJoy devices
- you need to execute UJPS as an administrator
- there are some issues currently with vJoy since a recent Windows update (https://github.com/shauleiz/vJoy/issues/20). A vJoy beta update is already available

**Comment by robert914** [comment]
Oh, duh! I totally overlooked the "Settings" button on the UI!! That's exactly what I was looking for. Sorry about that!

**Comment by 3noix** [comment]
No problem :-)

**Comment by robert914** [comment]
Yesterday was a long day ... :-)
